"""
Writer Agent
Receives analyst insights → uses Claude to write a full structured
markdown report → saves it via MCP file system tool → returns filename.
"""

from __future__ import annotations
import asyncio
import re
import sys, os
from datetime import datetime
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agents.base_agent import BaseAgent
from a2a.protocol import TaskRequest, TaskResult, TaskStatus
from mcp_servers.file_system_server import write_file


SYSTEM_PROMPT = """You are a professional research writer. Your job is to take analyst
insights and write a comprehensive, well-structured markdown report.

The report must include:

# [Title]
> One-line executive summary

## Overview
A 2-3 paragraph introduction explaining what this topic is and why it matters.

## Key Findings
Clear bullet points with the most important discoveries.

## Detailed Analysis
### [Sub-section 1]
### [Sub-section 2]
### [Sub-section 3]
In-depth prose for each major theme or finding.

## Trends & Future Outlook
What is changing, what to expect next.

## Key Players & Resources
Notable companies, tools, people, and links mentioned.

## Conclusion
2-3 paragraph wrap-up with actionable takeaways.

---
*Report generated by Multi-Agent Research Assistant*
*Powered by A2A + MCP + Claude*

Rules:
- Write in clear, professional English
- Use markdown formatting throughout
- Be specific — include names, numbers, dates where available
- Minimum 600 words
- Do NOT invent facts not present in the insights"""


class WriterAgent(BaseAgent):

    def __init__(self):
        super().__init__("WriterAgent")

    async def run(self, request: TaskRequest) -> TaskResult:
        job_id = request.job_id

        try:
            topic = request.context.get("topic", "Research Report")

            await self.emit_status(job_id, TaskStatus.WORKING, "Writing report")
            await self.emit_log(job_id, f"Writing full report on: '{topic}'")
            await self.emit_log(job_id, "Calling Claude to generate markdown report...")

            # ── Claude call ───────────────────────────────────────────────────
            user_prompt = f"""Write a comprehensive research report on: {topic}

Analyst insights to base the report on:
{request.input}

Write the complete markdown report now."""

            report_content = await self.ask_claude(
                system     = SYSTEM_PROMPT,
                user       = user_prompt,
                max_tokens = 8096,
            )
            # ─────────────────────────────────────────────────────────────────

            await self.emit_log(job_id, f"Report written — {len(report_content)} characters")

            # ── MCP Tool Call: write_file ─────────────────────────────────────
            filename = self._make_filename(topic)
            await self.emit_mcp(job_id, "write_file", inp=filename)

            saved_path = await asyncio.to_thread(write_file, filename, report_content)

            await self.emit_mcp(job_id, "write_file", inp=filename, out=f"Saved to {saved_path}")
            await self.emit_log(job_id, f"Report saved: {filename}")
            # ─────────────────────────────────────────────────────────────────

            await self.emit_status(job_id, TaskStatus.COMPLETED, f"Report saved: {filename}")
            return self.ok(request, filename)

        except Exception as e:
            await self.emit_log(job_id, f"Writing failed: {e}")
            await self.emit_status(job_id, TaskStatus.FAILED, str(e))
            return self.fail(request, str(e))

    def _make_filename(self, topic: str) -> str:
        """Convert topic to a safe filename with date prefix."""
        date   = datetime.now().strftime("%Y-%m-%d")
        slug   = re.sub(r"[^a-z0-9]+", "_", topic.lower()).strip("_")[:50]
        return f"{date}_{slug}.md"


# ── Singleton ──────────────────────────────────────────────────────────────────
writer_agent = WriterAgent()
